server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEndcoding=utf-8&useSSL=false&serverTimezone=UTC
    username: mysql
    password: password
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

mybatis:
  type-aliases-package: top.catoy.springcloud.entities
  mapper-locations: classpath:mapper/*.xml