server:
  port: 8006
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: nacos-client8006

server-url:
  nacos-user-service: http://nacos-provider/