server:
  port: 8761

eureka:
  instance:
    hostname: eurekaserver8716 #eureka服务端的实力名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己端就是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
